### ISSUE TITLE
gamma_gamma_fitter.py:66: RuntimeWarning: divide by zero encountered in log

### ISSUE THREAD

**Issue by jhurliman** [CamDavidsonPilon/lifetimes#134]
The documentation describes `frequency` as the number of time periods containing repeat purchases. I'm converting transactional SQL data to RFM so frequency in my case is `count(distinct date(date_trans)) - 1 as frequency`. This results in a zero for all customers who only made a single purchase. When feeding these samples into the GammaGammaFitter, at https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/fitters/gamma_gamma_fitter.py#L66 `log(frequency)` is calculated which causes a divide by zero runtime exception for those zero entries.

What is the correct fix for this?

1. Remove all samples with no repeat purchases from the GammaGammaFitter data set.
2. Change the definition of `frequency` for GammaGammaFitter to include the first purchase by adding 1 to the value.
3. Something else?

**Comment by CamDavidsonPilon** [comment]
Hey @jhurliman, the correct answer is 1. The implemented model only allows for repeat purchases. The docs [here](http://lifetimes.readthedocs.io/en/latest/Quickstart.html#estimating-customer-lifetime-value-using-the-gamma-gamma-model) do the filtering you suggest, too.

**Comment by DataNeel** [comment]
Forgive me if this isn't the right place for this question, but I've actually been working through this particular process recently. I've read the papers, the docs, and the BTYD documentation. Is there an intuitive reason that the first purchase is not included when modeling a customer's average purchase value? From a code standpoint, I can see why having 0 in the frequency column would result in all weight being placed on the overall average purchase value, but it is unclear to me why first purchases can't be considered for gamma-gamma modeling.

[Here's a stackexchange question I made on the subject just prior to seeing this issue](https://stats.stackexchange.com/questions/303891/why-isnt-the-monetary-value-of-the-first-transaction-used-in-the-gamma-gamma-sp), but I don't expect it to get any responses.

The BTYD walkthrough briefly mentions that intermediate steps of the transformation process are exposed so that a user can make slight changes, such as including first purchases by a customer.
That comment can be found on page 5 of [this doc](https://cran.r-project.org/web/packages/BTYD/vignettes/BTYD-walkthrough.pdf), end of section 2.1.

**Comment by adityaagarwal2001** [comment]
@CamDavidsonPilon I am running into same `RuntimeWarning: divide by zero encountered in log` even though my data is filtered for `frequency > 0`. 

```
returning_customers_summary = summary_data[summary_data['frequency'] > 0]
returning_customers_summary[['monetary_value', 'frequency']].corr()

ggf = lifetimes.GammaGammaFitter(penalizer_coef = 0.01)
ggf.fit(returning_customers_summary['frequency'], returning_customers_summary['monetary_value'])

summary_data['CLV_1year'] = ggf.customer_lifetime_value(
    transaction_prediction_model=model,
    frequency=summary_data['frequency'],
    recency=summary_data['recency'],
    T=summary_data['T'],
    monetary_value=summary_data['monetary_value'],
    time=12,
    discount_rate=0
).round(0)
```

Any thoughts?
