### ISSUE TITLE
Intuition behind ignoring the first purchase in gamma-gamma spend model

### ISSUE THREAD

**Issue by DataNeel** [CamDavidsonPilon/lifetimes#135]
Forgive me if this isn't the right place for this question. I've read the papers, the docs, and the BTYD documentation. Is there an intuitive reason that the first purchase is not included when modeling a customer's average purchase value? From a math/code standpoint, I can see why having 0 in the frequency column would result in all weight being placed on the overall average purchase value, but it is unclear to me why first purchases can't be considered for gamma-gamma modeling.

[Here's a stackexchange question I made on the subject just prior to creating this issue](https://stats.stackexchange.com/questions/303891/why-isnt-the-monetary-value-of-the-first-transaction-used-in-the-gamma-gamma-sp). It has a few more details.

The BTYD walkthrough briefly mentions that intermediate steps of the transformation process are exposed so that a user can make slight changes, such as including first purchases by a customer.
That comment can be found on page 5 of [this doc](https://cran.r-project.org/web/packages/BTYD/vignettes/BTYD-walkthrough.pdf), end of section 2.1.

**Comment by stochastic1** [comment]
It's a valid question. We've implemented the BG/NBD model by incrementing tenure by +1 so that tenure > recency always, and we seem to be able to use first-time buyers without a problem. Their value depends heavily upon the aggregate, but we have the wonderful good fortune that our mean spend per visit skews left enough that it strongly resembles a Gamma function.

That said, deviating from a theoretical basis always has to be done carefully. Customer acquisition is distinct from customer loyalty as a business question, and in marketing research has typically been modeled separately, both because of the nature of the problem (it's technically impossible to prove cross-sell to a first-time customer, and recommender systems can not be based on history) and because of the cost associated with it.

That said, using first-time customers in the context of the double-Gamma model may produce useful results, even if it isn't designed to model them.

**Comment by DataNeel** [comment]
Interesting. Thanks for sharing your experience!
