### ISSUE TITLE
conditional_expected_number_of_purchases_up_to_time shows weird values for ParetoNBDFitter

### ISSUE THREAD

**Issue by mwrabel** [CamDavidsonPilon/lifetimes#144]
It seems that conditional_expected_number_of_purchases_up_to_time method works weird for ParetoNBDFitter. Users with positive frequency and recency experience near zero estimate for predicted purchases, while those with frequency and recency =0 have higher values of predicted purchases. Not sure if it's a bug though, are you able to confirm?

You can easily replicate this with code below:
```python
from lifetimes.datasets import load_cdnow_summary
data = load_cdnow_summary(index_col=[0])

print(data.head())

from lifetimes import BetaGeoFitter
from lifetimes import ParetoNBDFitter

bgf = BetaGeoFitter(penalizer_coef=0.0) # 0.001 to 0.1 are effective (L2 regularization)
bgf.fit(data['frequency'], data['recency'], data['T'])
print(bgf)
pnbd = ParetoNBDFitter(penalizer_coef=0.0) # 0.001 to 0.1 are effective (L2 regularization)
pnbd.fit(data['frequency'], data['recency'], data['T'])
print(pnbd)

t = 30
data['pred_purchases_1m_bgf'] = bgf.conditional_expected_number_of_purchases_up_to_time(t, data['frequency'], data['recency'], data['T'])
data['pred_purchases_1m_pnbd'] = pnbd.conditional_expected_number_of_purchases_up_to_time(t, data['frequency'], data['recency'], data['T'])
print data.head(20)
```

![result](https://user-images.githubusercontent.com/17828920/32366921-851fb9e0-c080-11e7-9130-276fd74b0a3f.JPG)

**Comment by rhydomako** [comment]
I think I agree that there is a bug in `ParetoNBDFitter. conditional_expected_number_of_purchases_up_to_time`.

Starting with the above fitted model, take a look at what happens when I look at just a couple of rows:
```
t = 30
i = 3

pnbd.conditional_expected_number_of_purchases_up_to_time(
    t, 
    data['frequency'].head(i), 
    data['recency'].head(i),
    data['T'].head(i)
)
```

```
ID
1    0.010421
2    0.201782
3    6.422322
dtype: float64
```

Now, if I append a couple more rows to the conditional expectation calculation:
```
t = 30
i = 5

pnbd.conditional_expected_number_of_purchases_up_to_time(
    t, 
    data['frequency'].head(i), 
    data['recency'].head(i),
    data['T'].head(i)
)
```

```
ID
1    0.001851
2    0.035837
3    1.140608
4    1.140608
5    1.140608
dtype: float64
```

Notice that the first three rows have taken different values, which doesn't make much sense, since nothing in the expected purchase calculation depends on the number of input rows.

I think what is happening is that `ParetoNBDFitter. conditional_expected_number_of_purchases_up_to_time` calls `ParetoNBDFitter. _negative_log_likelihood`, which looks like it marginalizes its results and returns a scalar value. (Instead, what `ParetoNBDFitter.conditional_expected_number_of_purchases_up_to_time` really needs is the conditional likelihood for each row). So the marginalized likelihood (which depends on the number of input rows) is broadcasted over the rest of the dataframe in such a way that we don't run into any shape problems.

The solution here is probably to decouple the part that computes the conditional likelihood for each row. The optimization call can then sum them, while the expectation calculation can use the conditional terms individually.

**Comment by rhydomako** [comment]
@mwrabel I think the latest commits should make the ParetoNBD results more reasonable. When I tried your script after fixing the log-likelihood calculation, the comparison between the BetaGamma and ParetoNBD values was much closer.

**Comment by mwrabel** [comment]
@rhydomako Thank you for such a quick reaction! I'll try it out on few datasets soon! :+1:

**Comment by CamDavidsonPilon** [comment]
🎩 locally as well - values look good. Thanks @rhydomako!
