### ISSUE TITLE
What is a time period?

### ISSUE THREAD

**Issue by SreyaG** [CamDavidsonPilon/lifetimes#150]
I apologize for this naive question:
What is a time period in this context? My best answer is its a week, for the CDNOW data-set, so if a had my data in days it would be a day.

**Comment by stochastic1** [comment]
It's not a naive question, but rather it's a good question to ask how you should structure your data to use the model. 

I think the model is agnostic with respect to time period, so long as you can discretize no more than one purchase per time period. You're looking for incidence, and value per incidence. So if you have multiple purchases per week, you'll either have to aggregate to the week level, or shift your time period to reflect the minimum period that describes one purchase.

This did initially cause a problem with us with one particular customer who made a habit of purchasing twice per day, and we saw the problem in that the frequency of visits was higher than the number of periods (days), so we aggregated visits per day and we say that the model predicts likelihood to purchase one day in a given period.

**Comment by SreyaG** [comment]
Thank you for your answer it really helps to explain the concept. So in conditional_expected_number_of_purchases_up_to_time(t, data['frequency'], data['recency'], data['T']), the t represents the number of time periods right? So is it the probability of being alive for that specific time-period or the average over that those time-periods?

**Comment by stochastic1** [comment]
Hi @SreyaG , my understanding of that function is that t is the "time t" in "expected number of purchases up to t periods in the future". It's not the same as being alive for that specified period, but it is related. In the theory we do not actually observe "customer death" in a non-contractual setting, so we'd expect a customer who is not alive at time 0 would have 0 _actual_ purchases up until time t. 

The probability of being alive is given by a different method - and as the codebase has been updated since we began this conversation I'd recommend reviewing it again. Indeed, this is why I've come back to your question 4 months later is we need to update our process to consume the new codebase.
