### ISSUE TITLE
what is difference with Survival analysis

### ISSUE THREAD

**Issue by Sandy4321** [CamDavidsonPilon/lifetimes#154]
Thanks for your video about HR Building People Analytics - Keynote Cameron Davidson-Pilon
sorry for simple question, but regarding to this video
what is difference of lifetimes with Survival analysis

**Comment by CamDavidsonPilon** [comment]
Hey @Sandy4321, 

The difference is between contractual vs non-contractual relationships. Survival analysis deals with a contractual relationship, because the subject "dies" when the contract is broken (think of a subscription service). In a non-contractual relationship, we don't know when the subject "dies", as there is no contract to break. Does that help?

**Comment by AlexandreDecan** [comment]
Thanks for your answer, it helped me too! 
I think it could be interesting to add this in the documentation, especially for people like me who discovered lifetimes from lifelines :)
