### ISSUE TITLE
plot_period_transactions gives different graphs with the same model

### ISSUE THREAD

**Issue by rando128** [CamDavidsonPilon/lifetimes#205]
I've noticed that when I use the `plot_period_transactions()` function several times in a row (with the same trained model), I get slightly different graphs on the model frequency transactions. 

More concretely the following code will show 3 different graphs:

```python
from lifetimes.datasets import load_cdnow_summary

data = load_cdnow_summary(index_col=[0])

bgf = BetaGeoFitter(penalizer_coef=0.0)
bgf.fit(data['frequency'], data['recency'], data['T'])

plot_period_transactions(bgf)
plot_period_transactions(bgf)
plot_period_transactions(bgf)
```

Can anyone explain the reason for such a behaviour?

**Comment by CamDavidsonPilon** [comment]
There's a random data generation process in the background

**Comment by psygo** [comment]
> I've noticed that when I use the `plot_period_transactions()` function several times in a row (with the same trained model), I get slightly different graphs on the model frequency transactions. 

How much data do you have? I would expect the variations to smooth out once you have a big enough database...

It would be a curious and useful feature to have some sort of way of calculating the variance on the predictions given by the model itself though.

**Comment by zbazanowski** [comment]
Subsequent calls of the  plot_period_transactions routine yields slightly different results due to simulation implementation which is based on random number generator. I checked it up in the source code. It's fine.
But why did'n you applied the analytical results from “Counting Your Customers” the Easy Way:
An Alternative to the Pareto/NBD Model?
![image](https://user-images.githubusercontent.com/51027230/77911898-e1107d00-7291-11ea-9157-0ce373a50208.png)
Using formula (8) and taking into account the (age of each individual customer, you always get the exact result, no matter how many times you invoke the routine.
Or am I missing a hidden point in using the simulation instead of analytical approach? Maybe performance? (Eq. (8) is not trivial to calculate.)  Thank you guys.
