### ISSUE TITLE
In beta_geo_beta_binom_fitter, How to get n &  n_custs?

### ISSUE THREAD

**Issue by yanwu0105** [CamDavidsonPilon/lifetimes#216]
In `beta_geo_beta_binom_fitter.fit`  , will input  `n` &  `n_custs`.
How to measure the two parameters?

I don't understand the definition of n & n_custs.

**Comment by CamDavidsonPilon** [comment]
That's fair, I'm making this more clear in #220. 

`n` is the number of periods that the subject was observed for. I've renamed this `n_periods` to be more clear.
 
`n_custs` should be called `weights`, because that's how it's used in the log-likelihood. If you don't know what the weights should be, you can use an array of all 1s. (This too is made easier in #220)
