### ISSUE TITLE
How to get list of customers alive or dead ?

### ISSUE THREAD

**Issue by tanishksachdeva** [CamDavidsonPilon/lifetimes#218]
I know the library easily plots them on a beautiful heatmap. but what is the logic behind getting that data of dead and alive customers

**Comment by stochastic1** [comment]
@tanishksachdeva , are you using the plot_probability_alive_matrix() function for your heatmap?

**Comment by clausherther** [comment]
The `plot_probability_alive_matrix` function computes P(alive) for all **theoretical** combinations of recency and frequency up to the maxima in your datasets given the parameters computed during the `fit` step. It assumes customer age, `T` to be equal to the _maximum_ age of customers in your dataset.

You can also compute the **predicted probability of the customers in your dataset** like so.

(Where `rfm` is  pandas dataframe indexed by customer (e.g. from `summary_data_from_transaction_data()`) and 'model` is a fitted model (e.g. `BetaGeoFitter`) :
``` 
rfm["probability_alive"] = model.conditional_probability_alive(rfm["frequency"], rfm["recency"], rfm["T"])
```

**Comment by saran-p** [comment]
@stochastic1 @clausherther since "conditional_probability_alive" assumes customer age, T to be equal to the maximum age of customers in the dataset, is there a way to predict future probabilities? say i have a dataset ranging between 2018-2020 and want to find the probability of being alive in year 2050. Is there a way to find this?
