### ISSUE TITLE
Issue plotting P_alive 

### ISSUE THREAD

**Issue by alistairallan** [CamDavidsonPilon/lifetimes#231]
I'm running the following code in a local Jupyter Notebook. 
[https://github.com/susanli2016/Machine-Learning-with-Python/blob/master/CLV_Online_Retail.ipynb](https://github.com/susanli2016/Machine-Learning-with-Python/blob/master/CLV_Online_Retail.ipynb
)
I had an issue with `Matplotlib` after installing Lifetimes and had to reinstall via Conda. 

The code all runs as expected, predict works etc and all the plots run correctly **except** for `plot_history_alive` which only plots the `purchases`, but not `P_alive`. 

I get no errors or warnings. 

I can run predict on different period lengths for different customers and it runs fine, so might be related to the libraries? I had a quick look at the `plot_history_alive` function but I couldn't see any reason why it shouldn't work. 

I'm using:

```
matplotlib==2.2.2
pandas==0.23.4
lifetimes==0.9.1.0
```

Any ideas on where I should look first to debug? 

Thanks
A

**Comment by aprotopopov** [comment]
@alistairallan Do you have issues with all datasets or only with yours? Does the plot look correct with CDNOW data?

**Comment by teresadong** [comment]
I was able to get the CDNOW data to work see: https://colab.research.google.com/drive/1oc8vbnG-kHc_xaSZStNBH3e1R_VFboqb

But I wasn't able to get https://github.com/susanli2016/Machine-Learning-with-Python/blob/master/CLV_Online_Retail.ipynb to work.  Please see: https://colab.research.google.com/drive/15Ab4lbeai0TnVcaWOKF2ObpEtQVNnhuQ

![image](https://user-images.githubusercontent.com/3849181/59559061-acf2f680-8fb4-11e9-9815-97bbdac0c140.png)

In the original github, it looked like this:

![image](https://user-images.githubusercontent.com/3849181/59559067-cac05b80-8fb4-11e9-99d3-cd4407d1d74c.png)


The changes I made to the notebook were as follows:
I downgraded scipy from 1.2.0 to 1.1.0 because of: https://github.com/CamDavidsonPilon/lifetimes/issues/274

I commented out from lifetimes.estimation import * because it doesn't seem to exist anymore

Thanks!
Teresa

**Comment by maria-ferreira-olx** [comment]
I have the same issue, were you able to fix it?

**Comment by ZhengTzer** [comment]
I have the same issue, any solution?

**Comment by traveler1602** [comment]
I have the same issue as well.

**Comment by FakieKickflip** [comment]
Got the same issue today.  Any workarounds?

**Comment by fpannacci** [comment]
I'm having the same issue and following @FakieKickflip I discovered I have all ones. Do you know which can cause this? I have a dataframe in which all customers gets ones, I think is not possible

**Comment by FakieKickflip** [comment]
@fpannacci hard to figure out what is going on. In your plot the customer bought last in around 2014, 2015. It can not be right that he is an alive customer in 2021 and beyond.

**Comment by fpannacci** [comment]
Yes right...the data comes from here [https://www.kaggle.com/apoorvaappz/global-super-store-dataset] and the customer ID I'm looking at is NZ-18565
