### ISSUE TITLE
Calculating number of transactions between t, t+k given you are at t

### ISSUE THREAD

**Issue by vruvora** [CamDavidsonPilon/lifetimes#235]
Maybe I am doing something wrong but it feels that the current implementation of the RFM models is not truly helpful in predicting future transactions. For example, for calculating the expected number of transactions by month, we would do something like this: 

```python
for days, month in zip(range(30, 361, 30), range(1, 13)):
    expected_number_of_transactions = rfm_model.predict(days, frequency, recency, T) - rfm_model.predict(days - 30, frequency, recency, T)
    monthly_transactions[f'expected_number_of_transactions_month_{month}'] = expected_number_of_transactions
```

However, this often outputs a uniform number of transactions for the 12 months for each of the 12 months. 
![image](https://user-images.githubusercontent.com/4951479/49678622-5ff8fb00-fa3a-11e8-83fe-8ec6cdfc4c3e.png)

However, in reality, given the recency, frequency, and T knowledge, you should have asymmetric probabilities across the months. I could be implementing this incorrectly.

**Comment by vruvora** [comment]
@CamDavidsonPilon I think this feels off to me or it feels like a weird choice. 

https://github.com/CamDavidsonPilon/lifetimes/blob/9d6b1c5eeaaa1244730394c4a4eb3e4acf2f6c53/lifetimes/fitters/beta_geo_fitter.py#L211

**Comment by CamDavidsonPilon** [comment]
👋 hi @vruvora, thanks for the good issue

With respect to your first post, I'm curious why you think this uniform-like distribution isn't reasonable? Instead, what would you think is a better (more accurate) distribution? I believe the plot you have, given whatever your fitted parameters are + the model (BG/NBD?), looks reasonable. That's because it looks like this user has a low probability of dying, so the only decrease in their expected monthly purchases (which looks to be about 0.07 per month) is through this gradual attrition. 

With respect to your second post, 

> will give you the expected number of transactions relative to last purchase.

Why do you say that? AFAIU, `t+T` should represent the time `t` units after the latest time, `T`, which is usually what you want. 

>  But if you already know that the customer has been alive for 1500 days then the user would really care about
```rfm_model.predict(30 + (1500-1132), 3, 1132, 1500)```

Specifically, I don't follow this logic.

**Comment by vruvora** [comment]
So one of the thing that doesn't make sense to me about uniformity for those parameters is that as T -> infinity, expected future transactions should go to zero. RFM models should have a death rate of the customer backed in. For most of the experiments, I have run expected Number of Transactions seem to have a linear trend rather than expected number of transactions going to 0 as T approaches infinity.

**Comment by CamDavidsonPilon** [comment]
> RFM models should have a death rate of the customer backed in.

Agree. Part of the problem, I suspect, is that you are using a model that doesn't allow many deaths! If you are using the BG/NBD model, take a look at the "customer story" again. Remember that deaths can _only_ happen after a purchase event, and if a customer only makes 1 purchase every ~15months, then that's a very low chance of dying each month. Does that make sense? 

Generally, I'm now advocating for the BG/BB model instead of the BG/NBD model because of the internal paradox in the BG/NBD "customer story".

**Comment by vruvora** [comment]
Hmm. I will post graphs at some point but it seems that both BG/NBD and Pareto NBD have linearly increasing trends for expected purchases as T --> Infinity. I have not seen anything otherwise. Is there more documentation on BG/BB -- would love to use it.

**Comment by psygo** [comment]
> Hmm. I will post graphs at some point but it seems that both BG/NBD and Pareto NBD have linearly increasing trends for expected purchases as T --> Infinity.

*decreasing* or *increasing*?

If the exponential rate of decay is too small, then the trend will *seem* to go down linearly, but that is only a visual misunderstanding.
