### ISSUE TITLE
[Question] high correlation between frequency and monetary value

### ISSUE THREAD

**Issue by spatil13** [CamDavidsonPilon/lifetimes#269]
Hello Team, 

Based on article:  "The Gamma-Gamma submodel, in fact, assumes that there is no relationship between the monetary value and the purchase frequency. In practice we need to check whether the Pearson correlation between the two vectors is close to 0 in order to use this model"

I have two questions: 

1. In real world in most of cases there would high correlation between frequency visits/purchase to monetary value. I'm unable to understand importance of this assumption - Can someone please explain? 

2. In my case, a retail industry data - there is high correlation between monetary value and frequency. Is there a way I can use this model and produced valid results. 

PS: I have tried running this model on sample data. Transaction predictions are quit relevant however gamma - gamma model is producing highly inflated values. Not sure if it's because of highly correlated data or something else. 

Thank you.

**Comment by vierivincent15** [comment]
Hi, you may be understanding the concept of "monetary_value" not quite right. From what I understand from the docs, "monetary_value" of each customer is the average purchase per transaction (frequency) of each customer. So "monetary_value" is more of an average rather than summation.

(i.e.)
A has the following purchases: $2, $3, $4, $5, $6
B has the following purchases: $5, $10, $7.5

From this example, A will have frequency of 4 and monetary value of $4. B will have frequency of 2 and monetary value of $7.5

**Comment by spatil13** [comment]
that's helpful. I figured that few days after posting this question but forgot to update that here. I glad you did and thank you for your help. We have implemented this model and soon going to run in production. :)  I'm moving ahead and closing this issue. Once again, thank you.
