### ISSUE TITLE
Excluding monetary values first purchases

### ISSUE THREAD

**Issue by temakahap** [CamDavidsonPilon/lifetimes#276]
Hello !

Thanks a lot for such a great library, looking forward to start to use it.

I have question about monetary value. Could you please explain why it is necessary to exclude first purchases in monetary?

**Comment by psygo** [comment]
We exclude the first purchases, not only its monetary value. That's because the model deals with repeated transactions basically. But why it's defined like that I'm still not 100% sure, I've opened a similar issue to this one (#293), and will try to come back (and put the answer in the *docs*) as soon as I have an answer.

**Comment by psygo** [comment]
When you say exclude the first transactions, do you mean the masks inside the `expected_cumulative_transactions()` function?

That's a kind of obscure function but it isn't actually excluding the first purchases, it is only using the first transactions as a way of extrapolating how many purchases those *new* customers will make in the future. Take a look at the #298 *PR* and see if it helps.
