### ISSUE TITLE
How to evaluate the clv for long existing customers?

### ISSUE THREAD

**Issue by Kara035** [CamDavidsonPilon/lifetimes#285]
This is more like a *model question* instead of the package itself.

The model assumes the first purchase within the time period is the first purchase when the customer introduced to the company.

However, this is not always the case, since there are customers that exist two year or even longer if the company is not brand new.

In this case, would I still be able to get the prediction on the long existing customers? Or at least, would you have any suggestion that how I can evaluate the prediction for these type of customers fits in the model?

Thank you so much!

**Comment by myrthings** [comment]
If I understood it well this model is based in the "buy till you die" thing. So what it's important is in which probability they are alive or not. What we are looking for is each individual unique buying pattern.
I think you can get a good prediction for your long existing customers because they nowadays follow the same buying patterns than they had before you started collecting data. Or if they don't, it's more insightful how they behave in the present -maybe they change their lifestyle of whatever- for predicting the future, than how they behave in the past. I also think it's pretty common not having data since the first day.
It's an intuitive approach more than a technical one but hope it helps!

**Comment by psygo** [comment]
I'm not quite sure if I understood your question either but I'll try my best to answer.

This library works on RFM data, where *recency* is not only one of the main features, but probably the main one, as was mentioned by Prof. Peter Fader in [this](https://youtu.be/guj2gVEEx4s) lecture &mdash; which is also on the [main README](https://github.com/CamDavidsonPilon/lifetimes).

Due to the importance of *recency*, the model will automatically slowly kill inactive customers, even if they are old ones. The probability of them being alive will have a close-to-exponential decay and they will eventually *die*.

An option you have to deal with your scenario is to create a *window* of analysis. For example, you could force customers that have been in the data for more than 2 years to b deleted from the dataset.

If your problem is actually to account for customers' purchase behavior before the *window*, then you could simply (re)calculate their RFM for before that time period and then use the model on that. But do keep in mind that you might have to shift the other customers' (x, t_x, T) proportionately &mdash; simply preprocessing all of the customers in one batch would be far simpler.
