### ISSUE TITLE
Do Non-Contractual RFM Models deal well with Supermarket Data?

### ISSUE THREAD

**Issue by psygo** [CamDavidsonPilon/lifetimes#294]
With supermarkets, it seems reasonable to assume that there *will* be some periodicity to the purchases, because customers *do* regularly go to them. So my guess is that it's improper to use it for these cases (Non-Contractual RFM Models, such as the [Pareto/NBD](https://www.jstor.org/stable/2631608?seq=1#page_scan_tab_contents) or the [BG/NBD](https://repository.upenn.edu/marketing_papers/282/), assume that there is no periodicity to the customer's purchasing behavior).

Has anyone been able to reach good fits with these models for supermarket data?

In [Schmittlein's paper](https://www.jstor.org/stable/2631608?seq=1#page_scan_tab_contents), he goes on to make a table of use cases for the Non-Contractual setting. If anyone can answer my question I will try to transform this issue into a *PR* for a table of use cases within the docs.

**Comment by myrthings** [comment]
Hi @psygo,
I think it should be more interesting just to do a _PR_ with the hypothesis the data should follow instead of the type of business.
I mean, I've found that datasets that fit well with lifetimes (both in bg/nbd and gamma-gamma) follow a kind of exponential distribution for recency and frequency (without 0 values) and also for monetary values. But in my case recency follow a kind of normal distribution (but with a higher bar in the first values) and monetary values behaves normally too.
I don't know if there's any hypothesis on these for using the model, but it would be really interesting to add to the docs and also to know which alternatives to use instead.
Any idea? How does your dataset behaves on recency and monetary_value?

**Comment by psygo** [comment]
That's something I would like to add to the *docs* as well. But I'm as unsure as you are, and I haven't really invested that much time in it yet.

I've been trying to contact other researchers to see if they have a clue but haven't had any answers yet.

**Comment by psygo** [comment]
After exchanging some emails with a former researcher on this field (Prof. Annibal Parracho), he has told me that his RFM models fitted well with supermarket data. He also mentioned a recent related article, which I haven't yet looked at: 

> [*Predicting customer lifetime value for hypermarket private label products*](https://journals.vgtu.lt/index.php/JBEM/article/view/1223/961), Lin, Hsin-Hui; Li, Hsien-Ta; Wang, Yi-Shun; Tseng, Timmy H.; Kao, Ya-Ling; Wu, Min-Yi (2017), Journal of Business Economics and Management, 18(4), 619-635.

**Comment by psygo** [comment]
I've just exchanged a couple of emails about this topic with Prof. Bruce Hardie.

He told me that for *categories* we would probably *not* observe periodicity, even for supermarkets. However, that could be an issue for some products like milk. But that would be the exception. Another possibility for high periodicity is on the *store visits*.

Nevertheless, he remarks that we should first try to use simple models and then go for more complicated ones. He also adds that, if we need to account for some regularity, we should take a look at the models offered by the [BTYDplus](https://cran.r-project.org/web/packages/BTYDplus/index.html) library.
