### ISSUE TITLE
Error on import - Module 'scipy.misc' has no attribute 'logsumexp'

### ISSUE THREAD

**Issue by jonimatix** [CamDavidsonPilon/lifetimes#308]
Hi, 

During of the lifetimes package installation i am now getting the following error:

`module 'scipy.misc' has no attribute 'logsumexp'`

The more complete log:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
 in 
----> 1 from lifetimes.plotting import *

C:\ProgramData\Anaconda3\lib\site-packages\lifetimes\__init__.py in 
      3 from .version import __version__
      4 from .fitters import BaseFitter
----> 5 from .fitters.beta_geo_fitter import BetaGeoFitter
      6 from .fitters.beta_geo_beta_binom_fitter import BetaGeoBetaBinomFitter
      7 from .fitters.modified_beta_geo_fitter import ModifiedBetaGeoFitter

C:\ProgramData\Anaconda3\lib\site-packages\lifetimes\fitters\beta_geo_fitter.py in 
      7 import pandas as pd
      8 import autograd.numpy as np
----> 9 from autograd.scipy.special import gammaln, beta, gamma
     10 from scipy.special import hyp2f1
     11 from scipy.special import expit

C:\ProgramData\Anaconda3\lib\site-packages\autograd\scipy\__init__.py in 
      5 
      6 try:
----> 7     from . import misc
      8 except ImportError:
      9     pass

C:\ProgramData\Anaconda3\lib\site-packages\autograd\scipy\misc.py in 
      5 from autograd.numpy.numpy_vjps import repeat_to_match_shape
      6 
----> 7 logsumexp = primitive(scipy.misc.logsumexp)
      8 
      9 def make_grad_logsumexp(ans, x, axis=None, b=1.0, keepdims=False):

AttributeError: module 'scipy.misc' has no attribute 'logsumexp'

```

Apparently this is from the changes to the scipy module: `scipy.misc.logsumexp` is deprecated
at https://github.com/HIPS/autograd/issues/501

The fix should be as follows:

- Change from `scipy.misc import logsumexp` to `from scipy.special import logsumexp`

One of the solutions is to downgrade the scipy package which is not something I would like to do. 

Can you please update the package accordingly?

Thanks 
Jon

**Comment by psygo** [comment]
This is a problem I've also had, and, as you mentioned, should be fixed in the following releases.

It is sometimes difficult to fix them because libraries keep changing constantly. I think that one of the more robust ways would be to fix the requirements to static versions of the dependencies, instead of using `>=`. For example, if you downgrade `scipy` to `1.1.0` with `pip install -I scipy==1.1.0`, it should work.

The ideal situation should be to correct the code itself, like you said, though. However, while that doesn't happen you can use **virtual environments** in order to not mess with your local Python variables and setup. I've created a *PR* with a `Dockerfile` example that does work, but I would actually recommend you to use the [`pipenv`](https://github.com/pypa/pipenv) library, which is much simpler. For example:

```bash
(base) $ pipenv install scipy==1.1.0
(base) $ pipenv shell
(virtual_env_folder) (base) $ python
>>> import scipy
>>> scipy.__version__
'1.1.0'
```
