### ISSUE TITLE
wrong join in calibration_and_holdout_data()?

### ISSUE THREAD

**Issue by orenshk** [CamDavidsonPilon/lifetimes#310]
Shouldn't the pandas join in `combined_data = calibration_summary_data.join(holdout_summary_data, how="left")` be `combined_data = calibration_summary_data.join(holdout_summary_data, how="outer")`? According the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.join.html):

> left: use calling frame’s index (or column if on is specified)

which in this case leads me to think we're only keeping the calibration transactions?

Or maybe there's a reason to keep only customers that have bought something in the calibration period? Am I missing something? 

https://github.com/CamDavidsonPilon/lifetimes/blob/e9b3475ec81c3a036fd8087f50b65db70a651e75/lifetimes/utils.py#L125

P.S.
Thanks for making this awesome package!

**Comment by orenshk** [comment]
nm, I totally misunderstood what this was doing 😳

**Comment by psygo** [comment]
I think this is a good question. And I would advise you to at least state why you think your previous perception was mistaken.

You could use the `outer` join and extrapolate the model you've obtained with *only the calibration* (*training*) data onto the customers you *only find in the holdout* (*testing*) period. However, I believe it would be more proper to use only the data you have on both datasets &mdash; which is what the `left` join is doing. Otherwise how would predict purchases for customers that you don't even know exist yet?

Anyway, it would be a good experiment to try out, e.g., extrapolate purchases for new customers inside the *holdout* period *with* the fitted model from the *calibration* period. I will put it in the `docs` project I've opened some time ago &mdash; hopefully I'll go back to it soon.

What you're studying is closely related to an obscure `utils.py` function called `expected_cumulative_transactions()`. *PR* #298 was created to address its lack of documentation, try checking it out and see if it sheds some light on this problem.

**Comment by orenshk** [comment]
good point! Yes, my initial thought was that, since the BG/NBD model is only concerned with frequency, recency, and age, two different users with similar patters are effectively equivalent from the model's perspective and therefore testing the model on never seen users is a fair test. I hesitated because I'm not sure how the heterogeneity assumption fits into this. 

I'll experiment and update here as I learn more. I suppose it's worth reopening the issue for now.
