### ISSUE TITLE
Historical Recency Difficult to Interpret in Plots

### ISSUE THREAD

**Issue by dmanhattan** [CamDavidsonPilon/lifetimes#314]
https://github.com/CamDavidsonPilon/lifetimes/blob/299229ebc6b01431f46979c4eb75362159134ddf/lifetimes/plotting.py#L251

Hi Cameron,

I've had feedback from customers that the output for `plot_probability_alive_matrix()` and `plot_frequency_recency_matrix()` functions is difficult to interpret.

The functions return plots with 'Customer Recency' on the y axis that appears to be a measure of time between the start of the analysis period and the most recent purchase for each customer. This does not match the definition of 'Recency' used elsewhere in the package (i.e. the time from their first purchase to the most recent one).

This is causing confusion when they try to place 'new' customers (i.e. a small value of T) with a low value of recency on the plot.

Could the output be changed to show time between end of period and last purchase, so that the Y axis has a smaller value for customers who purchased more recently? This could be labelled 'Time since last purchase' to avoid conflict with the definition of Recency used in the underlying model.

Cheers,

Duncan

**Comment by psygo** [comment]
Sorry for the delay. Besides being busy with a ton of other things, I'm getting very rusty with this library. It's been more than 2 months since I had last studied the topic.

Anyway, there seems to be some topics that need clarification and that may solve your problem:

1. The `plot_probability_alive_matrix()` plots a 2D projection of the 3D RFM space plus colors for the model's probabilities of a customer being alive, thus we need to fix a value for `T` &mdash; the age of the customer at the customer at the observation period end &mdash;, which was chosen to be the maximum value of `T` in the given dataset or passed as the parameter `max_recency`.
    https://github.com/CamDavidsonPilon/lifetimes/blob/95b4d2a7dd7db47a857cad60f048c6a34bec5a09/lifetimes/fitters/beta_geo_fitter.py#L322-L324
    - In your case, with your example of a customer that has `recency = 30`, since the projection only considers customers who have age (`T`) near `700`, even though the customer is reasonably frequent (`10`),  it's been quite some time since his last purchase and so he will not have a high probability of being alive (he is a customer for `700` days but his last purchase was `670` days ago).
    - On a sidenote, I would like to add that the phenomenon of the decreasing alive probability with increased `frequency` (and `recency` fixed) *is actually normal*, not an error of `plot_probability_alive_matrix()`. It is empirically observed that the more people buy from a brand, the less they want to buy in the future &mdash; which seems reasonable, since people will think continuing to buy from the same brand as repetitive and with less aggregated value for them.
    - The difficulty in understanding *how* the `plot_probability_alive_matrix()` is created has been a source of trouble for multiple users in the past (see Issues #225, #226, #227), so I will try to write some better documentation for it. And making `T` an actual parameter is something I would like to improve within the library; if you wish to contribute on this area, you would be more than welcome.
1. The definitions of `recency` and `T` are indeed very strange when compared to the more intuitive, marketer's way of using the last day of the observation period minus the last purchase date, however the modeling literature has been like this for quite a while (e.g. Schmittlein's paper; maybe Issue #264 can help you a bit?). And that's because we need a way of using the customer's own "birth" as a reference point. If we use the usual, simpler marketer's definition we won't be able to accurately compare customer's to each other because they were born on different dates. As a bonus, here is how Schmittlein et al. put it in their text (they also don't go too much into the details; perhaps it was already a given in 1982?):
    > A customer who is alive at time `0` is observed up to time `T`. During this observation the customer will have made X purchases with the last purchase coming at `t`, `0 < t <= T`. Hence, the information on this customer contains 3 elements:
Information = (X, t, T).
For the model developed in this section, we show in the Appendix that these 3 elements represent all of the relevant information from the customer's transaction pattern. Our goal is to calculate the conditional probability
P(Alive | lnformation).
1. If you wish to use more palatable definitions of `recency` than what's used in the modeling of this library, you use something like the formula below:

    ```
    marketers_recency = (observation_period_end - customer_first_purchase) - 
                        (customer_last_purchase - customer_first_purchase)
                      = lifetimes_T - lifetimes_t_x
    ```
1. Whenever you post use cases or think there's something with the library and want to prove it, it is considered good practice to also post your model's parameters so we can validate that there wasn't anything wrong going on with the fitting, which could mess up your argument. In the case of this specific library, it is, in most cases, almost imperative to *also* show us the `plot_period_transactions()`, `plot_calibration_purchases_vs_holdout_purchases()` and `plot_incremental_transactions()` graphs, so we can be *almost* 100% sure that the problem *really is* with the library.
