### ISSUE TITLE
In the documentation, is the predicted_purchases example the probability of a purchase in the next period?

### ISSUE THREAD

**Issue by jnguyen32** [CamDavidsonPilon/lifetimes#340]
```
t = 1
data['predicted_purchases'] = bgf.conditional_expected_number_of_purchases_up_to_time(t, data['frequency'], data['recency'], data['T'])
data.sort_values(by='predicted_purchases').tail(5)
"""
       frequency  recency      T        predicted_purchases
ID
509   18          35.14        35.86    0.424877
841   19          34.00        34.14    0.474738
1981  17          28.43        28.86    0.486526
157   29          37.71        38.00    0.662396
1516  26          30.86        31.00    0.710623
"""
```

In this example from the documentation, `predicted_purchases` here is the probability of a customer making a purchase in the next period?

For example: ID #1516, the customer who has made 26 purchases, is the model suggesting that they have a 71% probability of making a purchase in the next 1 `t`?

What is `t` here? 1 day?

**Comment by psygo** [comment]
**It is the *number* of purchases, *not* the probability**. The probability is calculated elsewhere, in the `conditional_probability_alive`.

Your predicted purchases are all below `1`, and thus seem like probabilities, because you've chosen a small `t`, that is the amount of time you're giving the customers to make purchases. So, for example, customer `1516` will, on average, make `0.71` purchases in that length of time.

`t` is in *units of time*, it depends on what you've chosen for your data. If your data is in days, `t` should be measured in days, if it is in weeks, `t` should be in weeks.
