### ISSUE TITLE
Optimal Penalizer Coef

### ISSUE THREAD

**Issue by martingg92** [CamDavidsonPilon/lifetimes#387]
Hi everyone, somebody knows if there is a way to find the optimal penalizer coef ?? something like a gridsearch ???

I know that there is a way plotting the gamma distribution, but i have the doubt if there is a numerical combination. I have tried with differerent numbers of penalizer coef and studying the population mean, p, q, v and the negative log likehood and still dont find an answer. 

Here is an example.

![image](https://user-images.githubusercontent.com/42093381/88186830-b90fa580-cc03-11ea-8b48-18e7237f07ec.png)

In my context, the  best CLV (in terms of magnitude) is when i use a penalizer coef of 0.09, but i want to program a way when we use this method to find an optimal. 

Thanks!!!

**Comment by extrospective** [comment]
Coincidentally, I just filed another issue (https://github.com/CamDavidsonPilon/lifetimes/issues/388) which may be relevant for you.  

I do not think a value of q<1 should be accepted, as you see in my write up there.

And I am thinking of restricting regularization=0 for GammaGamma in my case because what the regularizer seems to be doing produces less than optimal results, and the impact on my metrics is hardly improved for the miniscule values where it is allowed.

I would encourage you to consider MAE or RMSE as measures of predictive success.   Also include penalizer=0 in your search/model as it may be optimal, and hopefully your population mean will be positive (otherwise isn't the model essentially broken)?
