### ISSUE TITLE
BG/NBD Model Not Converging

### ISSUE THREAD

**Issue by paint-it-black** [CamDavidsonPilon/lifetimes#405]
I have a dataset of 289K customers. When trying to run a BetaGeoFitter model with no penalizer, the model does not converge. With a large penalizer, it does converge (0.125 is the smallest such coef to converge) but the model sucks.

I tried removing some records to see if there are certain customers who are causing the model to break. My T value ranges up to 501. If I remove those who have a T greater than 497, the model with no penalizer does convert (I have no idea why). Customers with T >= 497 make up most of my data actually, roughly 2/3 of the data. As to why exactly this is causing the model to break I have no idea.

I'm not sure what is causing this and whether or not the BG/NBD model is even the most appropriate. For reference, this is the description of my rfm_data:

  | recency | frequency | T
-- | -- | -- | --
count | 289411 | 289411 | 289411
mean | 399.8754 | 176.6861 | 451.8257
std | 157.8627 | 146.9456 | 108.2
min | 0 | 0 | 0
25% | 335 | 38 | 481
50% | 495 | 150 | 500
75% | 501 | 295 | 501
max | 501 | 501 | 501

**Comment by hmikelee** [comment]
Dear Sir,

Maybe you can use plot_period_transaction from the bgf you got using 0.125
as penalizer, use large max_frequency. This way, It is easier for you to
visualize the original shape of the data n the fitting results.

Hope this helps.

Hmikelee

**Comment by paint-it-black** [comment]
This is what plot_period_transactions looks like when with that 0.125 penalizer model using a max frequency of 25 (anything larger just makes the plot really hard to look at)

![download](https://user-images.githubusercontent.com/73624529/97630397-a1e70d80-19d3-11eb-8d9f-38cace7c44c1.png)

If it helps, here is in the data how recency, frequency and T are distributed

**Recency:**
![download (1)](https://user-images.githubusercontent.com/73624529/97630834-33ef1600-19d4-11eb-82c9-6b800725e6bc.png)

**Frequency:**
![download (2)](https://user-images.githubusercontent.com/73624529/97630838-35b8d980-19d4-11eb-8f89-6165716306e0.png)

**T:**
![download (3)](https://user-images.githubusercontent.com/73624529/97630845-381b3380-19d4-11eb-9af5-67e6317de48d.png)

**Comment by cereusperuv** [comment]
@paint-it-black You have probably moved on from this problem a long time ago, but I just found your post and wanted to share my thoughts on a similar problem I've had.

I am working with a large customer base (~4M), which I am splitting into cohorts based on customer market and acquisition date, or actually when the customer is first observed in our receipt database. In our largest market, for the first few "acquisition months", I see a similar problem as yours. The BG-NBD model does not always converge, sometimes need a little "help" in the form of penalizer, and when it converges it is not a very good fit. See figure below for example. This is for the very first acquisition month cohort.

![image](https://user-images.githubusercontent.com/48787464/112816683-f2958c00-9081-11eb-9107-b64b06370fda.png)

The cohort in question is also very large, 600K+ customers. Below are the stats plots. I am not showing lifetime duration (T) because since I have based my cohorts on acquisition month the T:s are more less uniform on a 31 days range.

![image](https://user-images.githubusercontent.com/48787464/112819766-3342d480-9085-11eb-9c30-8e900048e415.png)

![image](https://user-images.githubusercontent.com/48787464/112819824-435ab400-9085-11eb-9b46-dd68ec6bc11f.png)

My take on this is that my problem stems from the receipts database being truncated before a certain date X months ago. Because of this, for the early cohorts in my data, actual new recruits are mixed with older customers that have been around for longer but that appear at that time because their earlier receipts are missing. These two segments are statistically very different. The older customers are by definition repeat customers, of various quality but nevertheless proven to be loyal. The actual new customers contain both customers that later on become loyal but also a portion that will not return for a second purchase (of course it is an entire spectrum, but figuratively speaking). That second portion is entirely absent among the old customers whose return purchases we observe. For this reason, a model specified in terms of a generative story for a coherent customer cohort is actually trying to fit against a mixture distribution of many (incomplete) cohorts during training, with all that means.

The problem naturally dies off away from the receipt cutoff. For instace, a year later the fit is much improved:

![image](https://user-images.githubusercontent.com/48787464/112822827-b9ace580-9088-11eb-928a-0065814655e8.png)

Btw, the zero-inflation problem can be somewhat mitigated by using the modified BG-NBD model:

![image](https://user-images.githubusercontent.com/48787464/112823020-02649e80-9089-11eb-87ec-cbe981cc5106.png)

Not sure this will help you out, or if you even need help any longer. I am curious however to hear your response on this.

Best, Robert
