### ISSUE TITLE
ValueError: Some values in recency vector are larger than T vector when data has no issue.

### ISSUE THREAD

**Issue by littlesweet1129** [CamDavidsonPilon/lifetimes#435]
I am trying to use the BetaGeoBetaBinomFitter, here is my fitting configuration
`bgbbf = BetaGeoBetaBinomFitter(penalizer_coef=0.001)
 bgbbf.fit(frequency = df_ch["frequency_cal"],
           recency = df_ch["recency_cal"],
           T = df_ch["T_cal"],
           n_periods = 30,
           weights = None,
           verbose = True,
           tol = 0.001)`
However it always raises an error saying "Some values in recency vector are larger than T vector". I checked the data, such issue does not exist, and the same dataset was able to be fitted using BetaGeoFitter. I am wondering if there is any issue with the BetaGeoBetaBinom Fitter?

**Comment by ColtAllen** [comment]
Hey @littlesweet1129,

`BetaGeoBetaBinomFitter.fit()` does not contain a `T` argument. Instead, use `n_periods = df_ch["T_cal"]`.

It's important to note `BetaGeoBetaBinomFitter` was originally developed for use cases involving discrete purchase periods (ie, restaurants with weekend brunch specials, a concert hall with an event calendar, etc.) If this does not describe your use case, I'd advise using another model.

I'm glad you brought this matter up, because I'm currently working on a successor library to `lifetimes` and will need to highlight these differences in the documentation:

https://github.com/ColtAllen/btyd

**Comment by littlesweet1129** [comment]
@ColtAllen Thank you for getting back to me! Yes, some more clarification around the model difference would definitely be helpful. I originally thought from reading the paper, `n_periods` were the number of time period between the discrete times of purchases? Is that not the case?

**Comment by ColtAllen** [comment]
If you go to Section 2.1 of the paper, it describes `n` as transaction opportunities, which is treated equivalently as 'n_periods' in the code. It also seems to be defined differently than 'T', which is based on the customer's perspective rather than the total opportunities available to all customers, so I'll modify my above message.

I responded to a similar memory overload issue in my repo for the successor library:

https://github.com/ColtAllen/btyd/issues/55

**Comment by SSMK-wq** [comment]
@ColtAllen - I also had the exact issue when I used the below fitter code

`bgf = BetaGeoFitter(penalizer_coef=0.001)
bgf.fit(clv['frequency'], clv['recency'], clv['T'])`

Only difference is my T values are in terms of years. So, they range from 1 to 5 years whereas my recency values are in days.

So, is it mandatory that they all have to be in same units (and we should stick to lifetimes way of representing/defining R,F,M and T). Actually I did my own definition of Recency, Frequency, Monetary and T and used fitter (from lifetimes) to build a model. But it doesn't work. So, am I doing anything wrong?

**Comment by ColtAllen** [comment]
Hey @SSMK-wq,

Are you using `BetaGeoFitter` instead of `BetaGeoBetaBinomFitter`? `T` (or `n_periods` for the latter) and `recency` need to be the same datetime units, so be sure to use the `freq` argument in `summary_data_from_transaction_data` to convert if needed.

Just to clarify for `BetaGeoBetaBinomFitter`, `T` cannot be used with this model because it expects a scalar `n_periods` representing total purchase opportunities, regardless of customer age. For example, if you're modeling concert attendance and there were 40 concerts, then n_periods=40 for all customers. Inputting an array with multiple values will break the model. I'm planning to change this parameter to an integer in an upcoming [btyd](https://github.com/ColtAllen/btyd) release so that this doesn't happen, but for now, create an `n_periods` column via `clv.assign(n=n_periods)`

**Comment by SSMK-wq** [comment]
@ColtAllen - Thanks this issue is solved from my end. Aligning them using utility function solved the issue.
