### ISSUE TITLE
Computing P(alive) Using the BG/NBD Model

### ISSUE THREAD

**Issue by jackyckma** [CamDavidsonPilon/lifetimes#44]
I found that for all one-time buyers, the P(alive)==1.0, which is rather strange.

And later I find in the paper http://www.brucehardie.com/notes/021/palive_for_BGNBD.pdf that it's the shortcoming of the mathematical formula being used since the model assume that death
occurs after a purchase and that customers are alive at the beginning of the
observation period. The paper also introduced a variant of the basic BG/NBD model which also estimate the number of dead at the beginning of observation period. It would be nice if that variant will be included in the library. I'm not yet able to figure out how to find the parameters of the likelihood function, may spend some time on it but not sure if I can make it since I don't have experience in solving likelihood function.

**Comment by rhydomako** [comment]
Hi @jackyckma, derivations for the Modified MG/NBD model are included in this paper http://research.sabanciuniv.edu/20/1/stvkaf01939.doc

I implemented the changes for this model locally, and it seems to work as promised in that one-time buys have an exponentially decaying P(alive). I've been meaning to put it into a PR, and now since there is some explicit interest, I'll try to put it together in the next couple days.

The only thing I'm trying to think through is that since the implementation is mostly modification of the BG/NBD model, whether it makes sense to almost duplicate most of the existing BG/NBD code with some modified coefficients, or to refactor some of the model class to make it as DRY as possible...

**Comment by rhydomako** [comment]
Take a look at the branch for #45 which has an implementation of this model.
