### ISSUE TITLE
NaN predictions for customers with 0 frequency and 0 recency

### ISSUE THREAD

**Issue by pavlo-seimskyi** [CamDavidsonPilon/lifetimes#442]
# Problem
I'm using `BetaGeoFitter` and have observed that in some cases the model produces `NaN` predictions for customers with frequency=0 and recency=0. This occurs when a customer makes only one transaction (their first) and never returns.

# Reason
The issue lies in the input to the logarithm function in the `conditional_expected_number_of_purchases_up_to_time` method. Specifically, it is [this line](https://github.com/CamDavidsonPilon/lifetimes/blob/41e394923ad72b17b5da93e88cfabab43f51abe2/lifetimes/fitters/beta_geo_fitter.py#L244). The term `_c` becomes negative if the fitted model parameters `a` and `b` sum to less than 1, as `_c = a + b + x - 1` and `x = 0` in this case. As a result, the output of `hyp2f1(_a, _b, _c, _z)` becomes negative, and taking the log of a negative number produces a `RuntimeWarning` and a resulting `NaN` prediction value.

```
RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
```

# Expected behavior
Ideally, the model produces predictions for those users with a frequency and recency of 0. Alternatively, it raises a warning that `a + b <= 1` if these parameter values are not expected.

# Context: Data details
I fitted the model to a cohort of customers with a high `T` value, between 1257-1287. Approximately 70% of the customers in this cohort have a frequency of 0 and recency of 0. The model is then used to predict for more recent customers whose `T` value may range between 0-1287 (that's when the `NaN` predictions occur). This seems to be in line with the implementation recommendation in the paper: _"the model should be applied separately to customer cohorts defined by the time (e.g., quarter) of acquisition"_.

**Comment by ColtAllen** [comment]
Hey @pavlo-seimskyi ,

Development on `lifetimes` ceased 3 years ago. Here's the link to the successor library: 
https://github.com/pymc-labs/pymc-marketing

I appreciate the deep dive you've done and information provided on this matter. The `NaN` predictions are due to the high `T` value, as described by the authors of the BG/NBD model in this PDF:

http://brucehardie.com/notes/027/bgnbd_num_error.pdf

The same PDF proposes a reformulation of the likelihood function to fix this issue, which we've implemented in `pymc-marketing`:

https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/clv/models/beta_geo.py#L143
