### ISSUE TITLE
Runtime Warning

### ISSUE THREAD

**Issue by rachelyee** [CamDavidsonPilon/lifetimes#445]
Experienced RuntimeWarning when trying to fit ParetoNBDFitter. I have removed NaN and negative values for the quantity my transaction data but I still get an error. Please advise how I can solve this issue.
**Code**
df= summary_data_from_transaction_data(data, customer_id_col='Customer_ID', datetime_col='Date')
pnf = ParetoNBDFitter(penalizer_coef=1e-06)
pnf.fit(df['frequency'], df['recency'], df['T'])

**Warning Message**
c:\Users\wqqs\Miniconda3\envs\env1\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
c:\Users\wqqs\Miniconda3\envs\env1\lib\site-packages\lifetimes\fitters\pareto_nbd_fitter.py:216: RuntimeWarning: invalid value encountered in logaddexp
  A_2 = logaddexp(-(r + x) * log(alpha + T) - s * log(beta + T), log(s) + log_A_0 - log(r_s_x))

**Comment by ColtAllen** [comment]
Hey @rachelyee,

Development on `lifetimes` ceased 3 years ago. Here's the link to the successor library:
https://github.com/pymc-labs/pymc-marketing

We're still finalizing the PR for `ParetoNBD` to fix this and other known issues with the `lifetimes` implementation, but for now, try using L-BFGS-B for the fit method and let me know how it goes:

`ParetoNBDFitter().fit(fit_method='L-BFGS-B', *args)`

**Comment by rachelyee** [comment]
Hi @ColtAllen ,
I have tried changing the fit method but got another warning message.

Optimize function with L-BFGS-B
c:\Users\wqqs\Miniconda3\envs\marketing\lib\site-packages\scipy\optimize\_numdiff.py:576: RuntimeWarning: invalid value encountered in subtract
  df = fun(x) - f0
<lifetimes.ParetoNBDFitter: fitted with 1603563 subjects, alpha: 829.34, beta: 790.13, r: 1.04, s: 1.05>

**Comment by BBDS-Colt** [comment]
Thanks for sharing `model.__repr__`; your model probably isn't converging properly due to the input data containing huge `T` values.

_alpha_ and _beta_ represent the scale parameters for the time between transactions and average customer lifespans in the population, respectively. Large values for both parameters often happen when training over many years of data. This can lead to DIV/0 errors in the model's likelihood and predictive methods, causing `RunTimeWarning` to be raised.

If your data is aggregated by day, try training on two years or less of data. If you have to include the full timespan, then in `summary_data_from_transaction_data()`, try aggregating your data by week or month instead of day. Both suggestions will reduce the scale of the `T` variable and should lead to more stable results.
