### ISSUE TITLE
Why the customers with 0 frequency has greater monetary value than others?

### ISSUE THREAD

**Issue by HunjaeJung** [CamDavidsonPilon/lifetimes#81]
Before I create this issue, I should say thank you to the all contributors about this great open source library.

Question below, 

Why the customers with 0 frequency(id 3,4,5,8,10 below) have greater monetary value than customer 2,8,9?

```
print ggf.conditional_expected_average_profit(
        summary_with_money_value['frequency'],
        summary_with_money_value['monetary_value']
    ).head()
"""
customer_id
1     24.658616
2     18.911480
3     35.171003
4     35.171003
5     35.171003
6     71.462851
7     18.911480
8     35.171003
9     27.282408
10    35.171003
dtype: float64
"""
```

I realized that "how" and "where" this results comes from. But I'm still curious "why" it should be. Is it intended?

```
def conditional_expected_average_profit(self, frequency=None, monetary_value=None):
     """
     # ...
     individual_weight = p * frequency / (p * frequency + q - 1)
     population_mean = v * p / (q - 1)
     return (1 - individual_weight) * population_mean + individual_weight * monetary_value
```

**Comment by CamDavidsonPilon** [comment]
@HunjaeJung good question - just for clarity and discussion, can you post the original data for those customers (i.e. the freq, rec, and M values)

**Comment by rhydomako** [comment]
Hi @HunjaeJung,

One thing about BTYD models is that they tend to treat customers with frequency=0 as non-informative. That is, if we've only seen one that customer one time, it is difficult to infer their average behaviour since we don't have any repeated data points.

That Gamma-Gamma model of monetary value is similar in that it doesn't claim to know the average purchase amount for frequency=0 customers since we've only seen one data point. So instead, the model assigns all those customers' expected average purchase amounts to be the same as the population mean.

So its not that those customers have a greater monetary value, rather, in this model they're just set to have the mean monetary value. We should expect to see a roughly similar number of customers with monetary values even greater than the frequency=0 customers.

There is a bit of discussion about this in http://www.brucehardie.com/notes/025/ : 

> We note that this is the weighted average of the population mean, E(Z), and the 
> observed average transaction value, \bar{z}. As the number of observations (x) 
> used to compute \bar{z} increases, less weight is placed on the population mean 
> and more weight is placed on the customer’s observed average.

We can see this in the function `conditional_expected_average_profit` -- if `frequency=0`, then it returns `population_mean`, but for large `frequency` the `individual_weight` term dominates and the `population_mean` is down-weighted. Intuitively, if we have many observations from an individual customer, we will put more weight on that customers average, otherwise default to the population mean.

**Comment by HunjaeJung** [comment]
@CamDavidsonPilon 
Thanks for reply, It's just from README.md of this repo :)

@rhydomako 
Thanks for clear explanation. "Non-informative" was the reason!
